image.bbclass: Update require processing
We only want to include the required config file if it is:

1) Enabled
2) The value is defined

This should resolve the layer index failure:

bb.parse.ParseError: ParseError in ${@['${WRTEMPLATE_CONF_WRIMAGE}',: not a BitBake file

by never returning WRTEMPLATE_CONF_WRIMAGE if it has not been set.

Signed-off-by: Mark Hatle <mark.hatle@windriver.com>