wrltemplate.bbclass: do not remove template related files for eSDK
Issue: LIN10-2139

We have code which remove wrlinux template related files (wrtemplate*.conf
and wrimage*.inc) in sdk_ext_postinst. These codes were trying to solve
the problem of eSDK for WRLinux not being able to be correctly installed.

For now, we do not have the above problem even without these codes. Besides,
these codes cause problem for eSDK updating. Error message is like below.

  ERROR: Updating conf/wrtemplate.conf failed

For eSDK updating, we will update meta data, we will update conf files
like local.conf and bblayers.conf. Overall, we will update our local eSDK
to the status of a remote eSDK. So, updating these template related files
to the remote ones should be safe, although they could be regenerated at
first build using eSDK according to the metadata in other conf files like
local.conf.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>